package com.tranwall.capital.client.i2c.enums;

public enum LoadControls {
  MAXIMUM_CARD_BALANCE_LIMIT("MX_CARD_BAL_LIMIT"),
  MAX_CARD_SUPPLEMENTARY_BALANCE_LIMIT_MAXIMUM_BALANCE_LIMIT_FOR_CARDHOLDER_MAX_CARD_WHOLE_BALANCE_LIMIT(
      "MX_BAL_LMT_CARD_SUPL"),
  MAX_FAMILY_BALANCE_LIMIT("MX_BAL_LIMIT_CH"),
  MONTHLY_LOAD_FREQUENCY("MX_WHOLE_BAL_LIMIT"),
  MONTHLY_LOAD_FREQUENCY_ON_MAIN_PURSE_CARDS("MX_FAMLY_BAL_LIMIT"),
  MONTHLY_LOAD_FREQUENCY_ON_MAIN_PURSES_SUPPLEMENTARY_PURSE_CARDS("MONTHLY_LOAD_FRQ"),
  MONTHLY_LOAD_FREQUENCY_ON_SUPPLEMENTARY_THEIR_PURSE_CARDS("MONTHLY_LOAD_FRQ_MP"),
  MONTHLY_FREQUENCY_OF_CARDHOLDERS_CARDS("MONTHLY_LOAD_FRQ_WF"),
  MONTHLY_LOAD_AMOUNT("MONTHLY_LOAD_FRQ_SP"),
  MONTHLY_LOAD_AMOUNT_SUPPLEMENTARY_PURSE("MONTHLY_LOAD_FRQ_CH"),
  MONTHLY_LOAD_AMOUNT_PURSE_CARDS("MONTHLY_LOAD_AMT"),
  LOAD_TRANSACTIONS_ON("MONTHLY_LOAD_AMT_MP"),
  ON_MAIN_PURSE_CARDS("MONTHLY_LOAD_AMT_WF"),
  ON_MAIN_PURSES_CARDS("MONTHLY_LOAD_AMT_SP"),
  ON_SUPPLEMENTARY_THEIR("MONTHLY_LOAD_AMT_CH"),
  MONTHLY_AMOUNT_OF_LOAD_TRANSACTIONS_ON_CARDHOLDERS_CARDS("DAILY_LOAD_AMT"),
  DAILY_LOAD_AMOUNT("DAILY_LOAD_AMT_MP"),
  DAILY_LOAD_AMOUNT_ON_MAIN_PURSE_CARDS("DAILY_LOAD_AMT_WF"),
  DAILY_LOAD_AMOUNT_ON_MAIN_PURSES_SUPPLEMENTARY_PURSE_CARDS("DAILY_LOAD_AMT_SP"),
  DAILY_LOAD_AMOUNT_ON_SUPPLEMENTARY_THEIR_PURSE_CARDS("DAILY_LOAD_AMT_CH"),
  DAILY_LOAD_AMOUNT_FOR_CARDHOLDER_N_DAYS_LOAD_AMOUNT("N_DAYS_LOAD_AMT"),
  N_DAYS_LOAD_AMOUNT_ON_MAIN_PURSE_CARDS("N_DAYS_LOAD_AMT_MP"),
  N_DAYS_LOAD_AMOUNT_MAIN_PURSES_SUPPLEMENTARY_PURSE_CARDS("N_DAYS_LOAD_AMT_WF"),
  N_DAYS_LOAD_AMOUNT_SUPPLEMENTARY_THEIR_PURSE_CARDS("N_DAYS_LOAD_AMT_SP"),
  N_DAYS_LOAD_AMOUNT_FOR_CARD_HOLDER("N_DAYS_LOAD_AMT_CH"),
  N_DAYS_LOAD_FREQUENCY("N_DAYS_LOAD_FRQ"),
  N_DAYS_LOAD_FREQUENCY_ON_MAIN_PURSE_CARDS("N_DAYS_LOAD_FRQ_MP"),
  N_DAYS_LOAD_FREQUENCY_MAIN_PURSES_SUPPLEMENTARY_PURSE_CARDS("N_DAYS_LOAD_FRQ_WF"),
  N_DAYS_LOAD_FREQUENCY_SUPPLEMENTARY_THEIR_PURSE_CARDS("N_DAYS_LOAD_FRQ_SP"),
  N_DAYS_LOAD_FREQUENCY_FOR_CARD_HOLDER("N_DAYS_LOAD_FRQ_CH");

  private String i2cLoadControl;

  LoadControls(String i2cLoadControl) {
    this.i2cLoadControl = i2cLoadControl;
  }
}
