package com.tranwall.capital.client.i2c.enums;

public enum MerchantGroup {
  UTILITIES("UT_MCG_CONFG"),
  RETAIL_STORES("RS_MCG_CONFG"),
  AUTOMOBILES_AND_VEHICLES("AV_MCG_CONFG"),
  MISCELLANEOUS_STORES("MS_MCG_CONFG"),
  SERVICE_PROVIDERS("SP_MCG_CONFG"),
  PERSONAL_SERVICE_PROVIDERS("PS_MCG_CONFG"),
  BUSINESS_SERVICES("BS_MCG_CONFG"),
  REPAIR_SERVICES("RR_MCG_CONFG"),
  AMUSEMENT_AND_ENTERTAINMENT("AE_MCG_CONFG"),
  PROFESSIONAL_SERVICES_AND_MEMBERSHIP_ORGANIZATIONS("SM_MCG_CONFG"),
  GOVERNMENT_SERVICES("GS_MCG_CONFG"),
  CLOTHING_STORES("CR_MCG_CONFG"),
  CONTRACTED_SERVICES("CS_MCG_CONFG"),
  AIRLINES("AL_MCG_CONFG"),
  AUTO_RENTALS("AR_MCG_CONFG"),
  HOTELS_AND_MOTELS("HM_MCG_CONFG"),
  TRANSPORTATION("TT_MCG_CONFG"),
  TRAVEL_AND_ENTERTAINMENT("TE_MCG_CONFG"),
  MISCELLANEOUS("MSL_MCG_CONFG"),
  WHOLESALE_DISTRIBUTORS_AND_MANUFACTURERS("WS_MCG_CONFG"),
  MAIL_PHONE_ORDER_PROVIDERS("OP_MCG_CONFG"),
  DIGITAL_GOODS_MEDIA("DG_MCG_CONFG"),
  RESTAURANTS("RES_MCG_CONFG"),
  GAS_STATIONS("GAS_MCG_CONFG"),
  EDUCATION("EDU_MCG_CONFG");

  private String i2cMerchantGroup;

  MerchantGroup(String i2cMerchantGroup) {
    this.i2cMerchantGroup = i2cMerchantGroup;
  }
}
