---
version: '3.9'

services:
  capital-db:
    image: 'postgres:13.4-alpine'
    container_name: capital-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_MULTIPLE_DATABASES: capital,fusionauth,capitaltest
    ports:
      - '${PGPORT:-5432}:5432'
    volumes:
      - ./local/database:/docker-entrypoint-initdb.d

  fusionauth:
    image: 'fusionauth/fusionauth-app:1.35.0'
    container_name: fusion-auth
    depends_on:
      - capital-db
    environment:
      - DATABASE_URL=jdbc:postgresql://capital-db:5432/fusionauth
      - DATABASE_ROOT_USERNAME=postgres
      - DATABASE_ROOT_PASSWORD=docker
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=docker
      - FUSIONAUTH_APP_MEMORY=128m
      - FUSIONAUTH_APP_RUNTIME_MODE=development
      - FUSIONAUTH_APP_URL=http://fusionauth:9011
      - SEARCH_TYPE=database
      - FUSIONAUTH_APP_KICKSTART_FILE=/usr/local/fusionauth/kickstart/kickstart.json
      - FUSIONAUTH_PORT=9011
    ports:
      - '9011:9011'
    volumes:
      - ./local/fusionauth/kickstart:/usr/local/fusionauth/kickstart


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles:
      - mon
    volumes:
      - ./local/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    profiles:
      - mon
    volumes:
      - ./local/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin@clearspend.com
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - '3000:3000'

  redis:
    image: redis:6.2.7
    restart: always
    container_name: redis
    command:
      - redis-server
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=password

  capital-ui:
    build: ./../capital-ui
    image: capital-ui:latest
    container_name: capital-ui
    profiles:
      - ui
    volumes:
      - ./local/capital-ui/configs/nginx:/etc/nginx/conf.d
    ports:
      - '9080:80'
