version: '3.9'

services:
  app:
    image: 'capital/core:latest'
    container_name: app
    profiles: ["full"]
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/capital
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docker
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_PROFILES_ACTIVE=docker
      - CLIENT_PLAID_SECRET=${CLIENT_PLAID_SECRET}
    ports:
      - '8080:8080'

  db:
    image: 'postgres:13.4-alpine'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=capital
