package com.clearspend.capital.controller.type.user;

import com.clearspend.capital.common.masking.annotation.Sensitive;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Value;

@Value
@RequiredArgsConstructor
public class ResetPasswordRequest {

  // a token generated by FusionAuth that is sent by email to the user
  // must be used to set a new password
  @JsonProperty("changePasswordId")
  private @NonNull String changePasswordId;

  @JsonProperty("newPassword")
  @Sensitive
  private @NonNull String newPassword;
}
