package com.clearspend.capital.controller.type.user;

import com.clearspend.capital.common.masking.annotation.Sensitive;
import com.clearspend.capital.controller.type.SteppedUpRequest;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Value;

@Value
@RequiredArgsConstructor
public class ResetPasswordRequest implements SteppedUpRequest<ResetPasswordRequest> {

  // a token generated by FusionAuth that is sent by email to the user
  // must be used to set a new password
  @NonNull String changePasswordId;

  @Sensitive String newPassword;
  String twoFactorCode;
  String twoFactorId;
  String trustChallenge;

  public ResetPasswordRequest(final String changePasswordId, final String newPassword) {
    this(changePasswordId, newPassword, null, null, null);
  }

  @Override
  public ResetPasswordRequest withTwoFactorParams(
      final String trustChallenge, final String twoFactorId, final String twoFactorCode) {
    return new ResetPasswordRequest(
        changePasswordId, newPassword, twoFactorCode, twoFactorId, trustChallenge);
  }
}
