spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:${PGPORT:5432}/capital
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:docker}
  jpa:
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
  flyway:
    clean-on-validation-error: false
    outOfOrder: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      client:
        clientId: ${SPRING_SECURITY_OAUTH2_CLIENT_CLIENT_ID:58b18750-7b73-4f6c-bd3c-a47b0a5bd9e6}
        secret: ${SPRING_SECURITY_OAUTH2_CLIENT_SECRET:d0rW31MMAlWW-04RIeFhkrzU7PuKzfoNBmrGo02vqp0}
      resourceserver:
        jwt:
          issuer-uri: ${client.fusionauth.base-url}

clearspend:
  business:
    limit:
      issuance:
        card:
          physical: 10
  ach:
    hold:
      place: false
  encryption:
    key:
      aes:
        current: j33ZKMytofk7Tw6836zlu0LyL1qaAGJ/9hM+ijbMKIc=
        0: j33ZKMytofk7Tw6836zlu0LyL1qaAGJ/9hM+ijbMKIc=
        next: 4OLeGOnzVQvR0vwGrFO3yMWu0Es6eOyODHhBidnw9DQ=
    fpe:
      pan:
        key: 148F8C2650959006B52D67A1E927A4D83DF6C967B8D4BA30C457EAF492F7C825
        tweak: 9F1E1761
  onboarding-validation: ${ONBOARD_EMAIL_PHONE_VALIDATION:true}

client:
  connect-timeout: 2000
  response-timeout: 5000
  read-timeout: 10000
  write-timeout: 10000
  fusionauth:
    api-key: ${FUSIONAUTH_API_KEY:TFNOproE4qBhUy1B8-coLoTfW-paQIzGKWK6yXzPv340Dkrk7fwHFDGx}
    base-url: ${FUSIONAUTH_BASE_URL:http://localhost:9011}
    application-id: ${spring.security.oauth2.client.clientId}
  google:
    storage:
      credentials: ${GCS_IMAGES_RECEIPTS_SA:<not set>}
      receiptBucketName: dev-images-receipts
      onboardFileBucketName: dev-images-onboard-file
      createBucket: true
      enabled: true

  plaid:
    clientId: 6148efa64491e20011af5b75
    environment: SANDBOX
    secret: ${PLAID_SECRET:}
  sendgrid:
    api-key: ${SENDGRID_API_KEY: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}
    notifications-sender-email: ${SENDGRID_NOTIFICATIONS_SENDER_EMAIL:ClearSpend <notifications@em4186.clearspend.com>}
    notifications-email-subject: ${SENDGRID_NOTIFICATIONS_EMAIL_SUBJECT:ClearSpend}
    onboarding-welcome-email-template-id: ${SENDGRID_ONBOARDING_WELCOME_EMAIL_TEMPLATE_ID:d-3215eacb40784ac6b6a96217196b17fe}
    kyb-kyc-pass-email-template-id: ${SENDGRID_KYB_KYC_PASS_EMAIL_TEMPLATE_ID:d-d27553e5452f4e3e9f7b097acb1b9738}
    kyb-kyc-fail-email-template-id: ${SENDGRID_KYB_KYC_FAIL_EMAIL_TEMPLATE_ID:d-b139358de5fe4f52ab3f4d7ce3306582}
    kyb-kyc-review-state-template-id: ${SENDGRID_KYB_KYC_REVIEW_STATE_TEMPLATE_ID:d-e80e529babfe486cae273287ea997764}
    kyb-kyc-require-additional-info-template-id: ${SENDGRID_KYB_KYC_REQUIRE_ADDITIONAL_INFO_TEMPLATE_ID:d-a1851b46169f482788e10f1e85c5e95d}
    kyb-kyc-require-doc-template-id: ${SENDGRID_KYB_KYC_REQUIRE_ADDITIONAL_INFO_TEMPLATE_ID:d-33f66fa9021f47d8a5b2811c4d967546}
    forgot-password-email-template-id: ${SENDGRID_FORGOT_PASSWORD_EMAIL_TEMPLATE_ID:d-0c078e558102456a9a492ad59a6d16f9}
    env-url: ${SENDGRID_ENV_URL:https://capital.dev.clearspend.com}
  stripe:
    # secret: "whsec_Mj59eXcGrzLDhheRIb7cXk8mfwUhPfCI" (Stripe CLI)
    issuing-secret: ${STRIPE_ISSUING_SECRET:whsec_5egOdj0En2NkrLxaj1kQlLgBN3aDn2xC}
    connect-secret: ${STRIPE_CONNECT_SECRET:whsec_ZyMUOUzPJUlvSzSO4eZDJnTsZmkhpP39}
    api-key: ${STRIPE_API_KEY:sk_test_51K4bTGGAnZyEKADzo2QvLZEYpQ4F7SUuK9041f6O7nIweNnEge9zr1yjiULB2ZvolgJPsfYrU64ClSzLTRqiMkMm00mR7wTpjw}
    allow-skip-stripe-header-validation: true
    clearspend_connected_account_id: ${STRIPE_CLEARSPEND_CONNECTED_ACCOUNT_ID:acct_1KPLzp4g2Xo63Nb8}
    clearspend_financial_account_id: ${STRIPE_CLEARSPEND_FINANCIAL_ACCOUNT_ID:fa_1KPLzt4g2Xo63Nb8uaQvsdmO}
    enable-telemetry: false
    connect-timeout: 30000
    read-timeout: 30000
    max-network-retries: 2
    # Terms of service acceptance ip address needed during stripe account creation.
    # Current value equals to clearspend domain public ip
    tos-acceptance-ip: ${STRIPE_TOS_ACCEPTANCE_IP:35.172.94.1}
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID:AC0a899d1f81a7443c707b2f66637b1ac3}
    auth-token: ${TWILIO_AUTH_TOKEN:a24434d31b817cf0f3acae9eba031cc1}
    message-service-id: ${TWILIO_MESSAGE_SERVICE_ID:MGe85d68add5ac0ddb5a2526241aa0369f}
    verify-service-id: ${TWILIO_VERIFY_SERVICE_ID:VA1545a989a4a0b547da6b42b1f579c243}
  clearbit:
    api-key: ${CLEARBIT_API_KEY:sk_2f09108fb81c88e6874543afaefac99c}
  codat:
    auth-token: ${CODAT_AUTH_TOKEN:NkJKUHVRZnBIYzdhY3VkUGhRVDFNM3FZWjdhTkE3UWFyeEJ2OE5YbA==}
    base-url: ${CODAT_BASE_URL:https://api.codat.io}

logging:
  level:
    root: INFO
    com.clearspend.capital: DEBUG

management:
  metrics:
    tags:
      application: capital-core
  endpoints:
    web:
      exposure:
        include: health,info,prometheus