plaid:
  clientId: 6148efa64491e20011af5b75
  environment: SANDBOX

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker

feign:
  url:
    i2c: https://ws2.mycardplace.com:6443/MCPWebServicesRestful/services/MCPWSHandler/
  okhttp:
    enabled: true
---

#Docker profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: docker
  jpa:
    hibernate:
      ddl-auto: none
