spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:16MB}
      max-request-size: ${MAX_REQUEST_SIZE:160MB}
  datasource:
    url: jdbc:postgresql://localhost:${PGPORT:5432}/capital
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:docker}
  jpa:
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
  flyway:
    clean-on-validation-error: false
    outOfOrder: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      client:
        registration:
          clientId: ${SPRING_SECURITY_OAUTH2_CLIENT_CLIENT_ID:58b18750-7b73-4f6c-bd3c-a47b0a5bd9e6}
          secret: ${SPRING_SECURITY_OAUTH2_CLIENT_SECRET:d0rW31MMAlWW-04RIeFhkrzU7PuKzfoNBmrGo02vqp0}
      resourceserver:
        jwt:
          issuer-uri: ${client.fusionauth.base-url}
  cache:
    # Redisson and spring redis provide different cache implementations (JCACHE and REDIS).
    # To avoid clashing a specific type can be specified.
    # Alternative approach is to implement custom CacheResolver bean
    type: REDIS
  redis:
    database: 0
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:password}
    timeout: ${REDIS_TIMEOUT:60000}

clearspend:
  business:
    limit:
      issuance:
        card:
          physical: 10
  ach:
    return-fee: ${CLEARSPEND_ACH_RETURN_FEE:20}
    hold:
      standard: ${CLEARSPEND_ACH_HOLD_STANDARD:false}
  encryption:
    key:
      aes:
        current: j33ZKMytofk7Tw6836zlu0LyL1qaAGJ/9hM+ijbMKIc=
        0: j33ZKMytofk7Tw6836zlu0LyL1qaAGJ/9hM+ijbMKIc=
        next: 4OLeGOnzVQvR0vwGrFO3yMWu0Es6eOyODHhBidnw9DQ=
    fpe:
      pan:
        key: 148F8C2650959006B52D67A1E927A4D83DF6C967B8D4BA30C457EAF492F7C825
        tweak: 9F1E1761
  onboarding-validation: ${ONBOARD_EMAIL_PHONE_VALIDATION:true}

client:
  connect-timeout: 2000
  response-timeout: 5000
  read-timeout: 10000
  write-timeout: 10000
  fusionauth:
    api-key: ${FUSIONAUTH_API_KEY:TFNOproE4qBhUy1B8-coLoTfW-paQIzGKWK6yXzPv340Dkrk7fwHFDGx}
    base-url: ${FUSIONAUTH_BASE_URL:http://localhost:9011}
    application-id: ${spring.security.oauth2.client.registration.clientId}
    step-up-valid-period-secs: 300
  google:
    storage:
      credentials: ${GCS_IMAGES_RECEIPTS_SA:<not set>}
      receiptBucketName: ${RECEIPT_BUCKET_NAME:dev-images-receipts}
      onboardFileBucketName: ${ONBOARD_FILE_BUCKET_NAME:dev-images-onboard-file}
      createBucket: true
      enabled: true

  plaid:
    clientId: 6148efa64491e20011af5b75
    environment: SANDBOX
    secret: ${PLAID_SECRET:}
  sendgrid:
    api-key: ${SENDGRID_API_KEY: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}
    email-notifications-enabled: ${SENDGRID_EMAIL_NOTIFICATIONS_ENABLED:true}
    notifications-sender-email: ${SENDGRID_NOTIFICATIONS_SENDER_EMAIL:ClearSpend <notifications@em8072.clearspend.com>}
    notifications-email-subject: ${SENDGRID_NOTIFICATIONS_EMAIL_SUBJECT:ClearSpend}
    onboarding-welcome-email-template-id: ${SENDGRID_ONBOARDING_WELCOME_EMAIL_TEMPLATE_ID:d-3215eacb40784ac6b6a96217196b17fe}
    kyb-kyc-pass-email-template-id: ${SENDGRID_KYB_KYC_PASS_EMAIL_TEMPLATE_ID:d-d27553e5452f4e3e9f7b097acb1b9738}
    kyb-kyc-fail-email-template-id: ${SENDGRID_KYB_KYC_FAIL_EMAIL_TEMPLATE_ID:d-b139358de5fe4f52ab3f4d7ce3306582}
    kyb-kyc-review-state-template-id: ${SENDGRID_KYB_KYC_REVIEW_STATE_TEMPLATE_ID:d-e80e529babfe486cae273287ea997764}
    kyb-kyc-require-additional-info-template-id: ${SENDGRID_KYB_KYC_REQUIRE_ADDITIONAL_INFO_TEMPLATE_ID:d-a1851b46169f482788e10f1e85c5e95d}
    kyb-kyc-require-doc-template-id: ${SENDGRID_KYB_KYC_REQUIRE_ADDITIONAL_INFO_TEMPLATE_ID:d-33f66fa9021f47d8a5b2811c4d967546}
    forgot-password-email-template-id: ${SENDGRID_FORGOT_PASSWORD_EMAIL_TEMPLATE_ID:d-0c078e558102456a9a492ad59a6d16f9}
    env-url: ${SENDGRID_ENV_URL:https://capital.dev.clearspend.com}
    password-reset-success-template-id: ${SENDGRID_PASSWORD_RESET_SUCCESS_EMAIL_TEMPLATE_ID:d-71d1284b1ec347ddb82249078c4edf76}
    welcome-invite-only-template-id: ${SENDGRID_WELCOME_INVITE_ONLY_EMAIL_TEMPLATE_ID:d-391f46e5b79248f293377162fe50b818}
    kyb-kyc-docs-received-template-id: ${SENDGRID_KYB_KYC_DOCS_RECEIVED_EMAIL_TEMPLATE_ID:d-fbd177a8de2a43ec8c50bbb58ea65fdb}
    bank-details-added-template-id: ${SENDGRID_BANK_DETAILS_ADDED_TEMPLATE_ID:d-044986ffaf204424a8fc10f2b526fe73}
    bank-funds-available-template-id: ${SENDGRID_BANK_FUNDS_AVAILABLE_TEMPLATE_ID:d-6067636fa5d14c509adc47a4a274fa71}
    bank-details-removed-template-id: ${SENDGRID_BANK_DETAILS_REMOVED_TEMPLATE_ID:d-34483e8234504cb19bd11eb36375d15a}
    bank-funds-return-template-id: ${SENDGRID_BANK_FUNDS_RETURN_TEMPLATE_ID:d-ca472219db95445c94498f4d09e28ee4}
    bank-funds-withdrawal-template-id: ${SENDGRID_BANK_FUNDS_WITHDRAWAL_TEMPLATE_ID:d-07d7a578a0754e668e9dd601677d55da}
    card-issued-notify-owner-template-id: ${SENDGRID_CARD_ISSUED_NOTIFY_OWNER_TEMPLATE_ID:d-c383489d5e114c80953b2a1527c4533a}
    card-issued-virtual-notify-user-template-id: ${SENDGRID_CARD_ISSUED_VIRTUAL_NOTIFY_USER_TEMPLATE_ID:d-a7bf2b56108e4f9e8675ef36c24ad4fa}
    card-issued-physical-notify-user-template-id: ${SENDGRID_CARD_ISSUED_PHYSICAL_NOTIFY_USER_TEMPLATE_ID:d-4af0d801e7d542bbae3ca15d0a93c721}
    card-shipped-notify-user-template-id: ${SENDGRID_CARD_SHIPPED_NOTIFY_USER_TEMPLATE_ID:d-daa03219d41c4a28bedc7a2607d29109}
    card-start-activation-template-id: ${SENDGRID_CARD_ACTIVATE_START_TEMPLATE_ID:d-766c4fb9c2fb4974828add3c94e8a9ff}
    card-activation-completed-template-id: ${SENDGRID_CARD_ACTIVATION_COMPLETED_TEMPLATE_ID:d-852d5c75ec7644cca7535b2f4fbf7286}
    card-frozen-template-id: ${SENDGRID_CARD_FROZEN_TEMPLATE_ID:d-7fdf02b4c08b4f54bb73c4c977652321}
    card-cancelled-template-id: ${SENDGRID_CARD_CANCELLED_TEMPLATE_ID:d-2e07e8adbb414210a443af59135ee5a9}
    card-unlinked-template-id: ${SENDGRID_CARD_UNLINKED_TEMPLATE_ID:d-167fae5fd7514c3da8bbdc190db18d9d}
    card-unfrozen-template-id: ${SENDGRID_CARD_UNFROZEN_TEMPLATE_ID:d-8aa17f4296c74c50bf86786540fab6d3}
    user-details-updated-template-id: ${SENDGRID_USER_DETAILS_UPDATED_TEMPLATE_ID:d-dedcc52329e1403f90986802aefeb6c6}
    user-account-created-template-id: ${SENDGRID_USER_ACCOUNT_CREATED_TEMPLATE_ID:d-5082896f143c46d886893ae08193a397}
    bank-funds-deposit-request-template-id: ${SENDGRID_BANK_FUNDS_DEPOSIT_REQUEST_TEMPLATE_ID:d-46c77ecdafd545a9a33384d763fd96ad}
    bank-funds-deposit-request-scheduled-action-template-id: ${SENDGRID_BANK_FUNDS_DEPOSIT_REQUEST_SCHEDULED_ACTION_TEMPLATE_ID:d-60669e8099b246f193dd29bc73a3278e}
    financial-account-ready-template-id: ${SENDGRID_FINANCIAL_ACCOUNT_READY_TEMPLATE_ID:d-b69e6245a61a4f0593ed3de9726cd7ec}
  stripe:
    # secret: "whsec_Mj59eXcGrzLDhheRIb7cXk8mfwUhPfCI" (Stripe CLI)
    issuing-secret: ${STRIPE_ISSUING_SECRET:whsec_5egOdj0En2NkrLxaj1kQlLgBN3aDn2xC}
    connect-secret: ${STRIPE_CONNECT_SECRET:whsec_ZyMUOUzPJUlvSzSO4eZDJnTsZmkhpP39}
    api-key: ${STRIPE_API_KEY:sk_test_51K4bTGGAnZyEKADzo2QvLZEYpQ4F7SUuK9041f6O7nIweNnEge9zr1yjiULB2ZvolgJPsfYrU64ClSzLTRqiMkMm00mR7wTpjw}
    allow-skip-stripe-header-validation: true
    clearspend_connected_account_id: ${STRIPE_CLEARSPEND_CONNECTED_ACCOUNT_ID:acct_1KPLzp4g2Xo63Nb8}
    clearspend_financial_account_id: ${STRIPE_CLEARSPEND_FINANCIAL_ACCOUNT_ID:fa_1KPLzt4g2Xo63Nb8uaQvsdmO}
    enable-telemetry: false
    connect-timeout: 30000
    read-timeout: 30000
    max-network-retries: 2
    # Terms of service acceptance ip address needed during stripe account creation.
    # Current value equals to clearspend domain public ip
    tos-acceptance-ip: ${STRIPE_TOS_ACCEPTANCE_IP:35.172.94.1}
    # Enable special amounts that will fail stripe transfers
    # More details:
    # https://stripe.com/docs/treasury/beta/api-spec/moving-money#inbound-transfers-test-mode
    # https://stripe.com/docs/treasury/beta/api-spec/moving-money#outbound-transfers-test-mode
    # Inbound transfers:
    # 131$ - pm_usBankAccount_noAccount
    # 132$ - pm_usBankAccount_invalidAccountNumber
    # 133$ - pm_usBankAccount_dispute
    # Outbound transfers:
    # 141$ - pm_usBankAccount_canceledByUser
    # 142$ - pm_usBankAccount_internalFailure
    # 143$ - pm_usBankAccount_accountClosed
    # 144$ - pm_usBankAccount_invalidAccountNumber
    enable-transfer-failures: ${STRIPE_ENABLE_TRANSFER_FAILURES:true}
    # For test webhooks we might want to delegate the auth request to another endpoint since stripe
    # can only deliver auth event to one instance only (unlike other events).
    # If left blank no fallback will be attempted
    auth-fallback-url: ${STRIPE_AUTH_FALLBACK_URL:}
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID:AC0a899d1f81a7443c707b2f66637b1ac3}
    auth-token: ${TWILIO_AUTH_TOKEN:a24434d31b817cf0f3acae9eba031cc1}
    message-service-id: ${TWILIO_MESSAGE_SERVICE_ID:MGe85d68add5ac0ddb5a2526241aa0369f}
    verify-service-id: ${TWILIO_VERIFY_SERVICE_ID:VA1545a989a4a0b547da6b42b1f579c243}
  clearbit:
    api-key: ${CLEARBIT_API_KEY:sk_2f09108fb81c88e6874543afaefac99c}
  codat:
    auth-token: ${CODAT_AUTH_TOKEN:ZVZvb2RHdXl4ejZhZHJQMGpaQ0JkU2pzajNmY1RXUkRGUnBqTlZYbQ==}
    base-url: ${CODAT_BASE_URL:https://api-uat.codat.io}
    auth-secret: ${CODAT_AUTH_SECRET:eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY0NTY0NDAzMiwiaWF0IjoxNjQ1NjQ0MDMyfQ}
    quickbooksonline-code: ${CODAT_QBO_CODE:quickbooksonlinesandbox}
    connect-timeout: 2000
    response-timeout: 15000
    read-timeout: 15000
    write-timeout: 10000
    # This value is a ratio of the 'matching score' to the total number of characters to match.
    # Minimum Value = 0, Maximum Value = 2
    supplier-matching-ratio: 0.5
  mx:
    base-url: ${MX_BASE_URL:https://int-api.mx.com}
    auth-secret: ${MX_AUTH_SECRET:NmRjYTk0MjEtNDdkMy00Y2YzLThkZDAtZGVkNjQwMDlkNzZmOmY0M2IwZjUyZTg1M2YwZDY1OTg0MjdlNjlhMjUwMzU3MTZlZjliMjE=}
    connect-timeout: 2000
    response-timeout: 15000
    read-timeout: 15000
    write-timeout: 10000
    use-mx-logos: true
  bigtable:
    project-id: ${BIGTABLE_PROJECT_ID:silken-facet-324217}
    instance-id: ${BIGTABLE_INSTANCE_ID:dev-bigtable}
    credentials: ${GCS_BIGTABLE_SA:<not set>}
  firebase:
    credentials: ${FIREBASE_CREDENTIALS:{"type":"service_account","project_id":"firebase-dev-346321","private_key_id":"7f8687381c1634a18de1db02b9b082c76f02cd25","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCiXpzzA7Igscp1\nLjLOmhUKpAcgVFQv5zkFT1rREKcf9yDpn8EqNq/WBGm19d6rVpakg8CYgB4IrTXs\nSS5VcyfGikqSOh8ZlbuCRVhTRbjnqLt6UGyiDctOqdChvfPOySDg9Y6q7hyD1FQ6\nrHEwDqUyT7lcqYq1ylllE5bbQZ1p5rB7BCFli60n+6hJtghGyMMp+sTmPNprhdbc\n6SApVZTPpRtFGlNqAyhOY4/vq4JcwhbupW5ABMqCkCzqFjX5GynJgNC3MnusQulF\ncrAFNmxlZJlQGQQUz1KLKZdTGIptI4OJ/FPsQFqi80FLDIe3gcdAdO2jPFi/zsWY\nzgMt7EvxAgMBAAECggEAB4TwKcTjC+aP5KtWCQFTtiFwfwvItksz9c39+66UvsM4\nD/mo/WZ48CVWK+oN/MtOwKGlWqqcOXSkCaQ99BEYJ3aiC3GLnSi0/Uxu0bRp4riK\nrhhpX3vaDXOJyOO+FbZ0wlY83CeYxHYhzHHN8BbNia3tfKARX2fWifrFQrQgMRY9\n9Oyi6prI3mNwpEuOhKs/e2Y4pepQD09YPdalV3AG+HiPrUbh64m0xFcTY7aYTSj+\n8XfOLLhT1HnbkMvPzdi2N5b+OukJ/ai8GXk7AZ6nTdJKx1VFEh0FYgOw0fvxhXpU\nXcfCRLyzIwTSwq0koBJdsEdnJO4rxEAWj1tDdJU7vQKBgQDP7G7pF2iGxfbSJxgt\nm7hnGgyS1HNGsY2Z9r1f/KTbYoMZN6pPKgPEHJMI5+oOCsbcGEp5xKU7T1WCyOTr\nx51PJl3qYqKZMorzO0LqS0wrFJFr0qtE58gzNU1ip7tx1ZWYbPUPohr/VVfCdo8w\nSfWGwkw+gr7oQOz6GHGhWl/xwwKBgQDH6bbjg447ywH3Tou8HWB6isSbfpnr/NMT\n49GQ7pQC2jxlmSg4AUX3S7kZ5nBkvH1JpMd1UsJJNPFG9tE/7nmL/5C81rC0cjwS\niELLeYA8C8blfL/0B9JyVQKu1aR/SzsZv8/YXXbu2o7yLXx4+xYu5M3jes0sz96b\nDCR5dQTcOwKBgQCj3MB34KPW+zMO4hKS9xM35faczOPghdOD0Enk2NYPs65/9De7\nVfBL4P0b2rHByUp5cIdZOdnCST6p6KtJCjL2itUfAAcG1ydck4qj3R21IeuNXyTt\nFAHaIZrQMkJubxYLX2sum+HM8rRMJGWqd88RGhU+eon7vhdE7ni24eOVQwKBgAyC\ndnxULiFVucDE/H+AAxqH9neYe39F6dtzxRhhpYdsKp1c8SRYCA3KgkG5pszW8qwa\nEJUp4Zh9JKABL+TlQlvdWSxH7vTLtTCfsDZVWw3m2sJfhQ97MdMPuMRCADIq/f7F\nfvcWGiwmJw3GhOR5KdEzZiLW+2HTfCWNo/apuO0jAoGBAJ7GBwWJ4mJHVhKknxvV\nQziChBvU5LPqNIrKuGbGgSEXK50aDromFMXkfIO2pTDa2V64j5jvGpyEoPkI7neE\nwRbPlShgCPk/dKNQfjnYxeEXivMfyHuUy/m1ffktYUg0SLgqkIIHNYfZ+buvYmWj\n5ptRpmp2neHNE0Jbt0N7TXHv\n-----END PRIVATE KEY-----\n","client_email":"firebase-adminsdk-9dqot@firebase-dev-346321.iam.gserviceaccount.com","client_id":"100931572749066156926","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-9dqot%40firebase-dev-346321.iam.gserviceaccount.com"}}

logging:
  level:
    root: INFO
    com.clearspend.capital: DEBUG
    com.clearspend.capital.common.data.util.HttpReqRespUtils: WARN
    com.clearspend.capital.configuration.filter.RequestFilter: WARN
  execution-time:
    enabled: ${CAPITAL_LOGGING_EXECUTION_TIME_ENABLED:true}
    level: ${CAPITAL_LOGGING_EXECUTION_TIME_LEVEL:WARN}       # logging level
    mode: ${CAPITAL_LOGGING_EXECUTION_TIME_MODE:all}          # all - all spring methods/annotation - annotated methods only
    threshold: ${CAPITAL_LOGGING_EXECUTION_TIME_THRESHOLD:300}  # if execution time exceeds threshold - execution will be logged

management:
  metrics:
    tags:
      application: capital-core
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
async:
  core-pool-size: 2
  max-pool-size: 2
  queue-capacity: 500
  thread-name-prefix: async-executor-

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
      port: 8086
    database:
      skip-create: true
      type: sql
    job:
      default-number-of-retries: 10
      retry-back-off-time-seed: 3
    job-scheduler:
      enabled: true
    miscellaneous:
      allow-anonymous-data-usage: false # this is true by default