spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:${PGPORT:5432}/capital
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:docker}
  jpa:
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
  flyway:
    clean-on-validation-error: false
    outOfOrder: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      client:
        clientId: ${SPRING_SECURITY_OAUTH2_CLIENT_CLIENT_ID:58b18750-7b73-4f6c-bd3c-a47b0a5bd9e6}
        secret: ${SPRING_SECURITY_OAUTH2_CLIENT_SECRET:d0rW31MMAlWW-04RIeFhkrzU7PuKzfoNBmrGo02vqp0}
      resourceserver:
        jwt:
          issuer-uri: ${client.fusionauth.base-url}
tranwall:
  encryption:
    key:
      aes:
        current: j33ZKMytofk7Tw6836zlu0LyL1qaAGJ/9hM+ijbMKIc=
        0: j33ZKMytofk7Tw6836zlu0LyL1qaAGJ/9hM+ijbMKIc=
        next: 4OLeGOnzVQvR0vwGrFO3yMWu0Es6eOyODHhBidnw9DQ=
    fpe:
      pan:
        key: 148F8C2650959006B52D67A1E927A4D83DF6C967B8D4BA30C457EAF492F7C825
        tweak: 9F1E1761

client:
  connect-timeout: 2000
  response-timeout: 5000
  read-timeout: 10000
  write-timeout: 10000
  alloy:
    url: https://sandbox.alloy.co/v1/
    individual:
      token: hyGpn2Lrdo04eLiolXSHAAsUJghQHxO4
      secret: s25ZtYvujLaIypNeXbw5ZvhpYh5RD3VQ
    business:
      token: ylU99zgb9lI8EtVfHzYWmGBEWqqYHUdX
      secret: oLvy6KLi7I0kAcIYsc4RpsYfoSVBdx4s
    document:
      token: GGNSWsFr2Tm86QIMi37gzKpZ0sFfxUqZ
      secret: c7ZbBLm5mHdqhrAGbaYfAdxrbhG815oE
    group:
      token: EE3h7zPppYwdEDBS4gNNT2GRrEydrbok
      secret: fx6TWSPSlFQCNz8TQ2Q46CamEjK0pd1B
  fusionauth:
    api-key: ${FUSIONAUTH_API_KEY:TFNOproE4qBhUy1B8-coLoTfW-paQIzGKWK6yXzPv340Dkrk7fwHFDGx}
    base-url: ${FUSIONAUTH_BASE_URL:http://localhost:9011}
    application-id: ${spring.security.oauth2.client.clientId}
  google:
    storage:
      credentials: ${GCS_IMAGES_RECEIPTS_SA:<not set>}
      receiptBucketName: dev-images-receipts
      createBucket: true
      enabled: true
  i2c:
    url: https://ws2.mycardplace.com:6443/MCPWebServicesRestful/services/MCPWSHandler/
    acquirerId: TW0001
    userId: TWTest
    password: "{TWTest_Temp@/110}"
    stakeholder-program:
      id: tranwall_virtual_SDK
      bin: 601999
    virtual-program:
      id: tranwall_virtual
      bin: 601999
      starting-numbers: 6019990022
    plastic-program:
      id: transwall_test
      bin: 601999
      starting-numbers: 601999002
    push:
      userId: "replace-me"
      password: "replace-me-too"
  plaid:
    clientId: 6148efa64491e20011af5b75
    environment: SANDBOX
    secret: ${PLAID_SECRET:}
  sendgrid:
    api-key: ${SENDGRID_API_KEY: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}
    notifications-sender-email: ${SENDGRID_NOTIFICATIONS_SENDER_EMAIL:ClearSpend <notifications@em6632.clearspend.com>}
    notifications-email-subject: ${SENDGRID_NOTIFICATIONS_EMAIL_SUBJECT:ClearSpend}
    onboarding-welcome-email-template-id: ${SENDGRID_ONBOARDING_WELCOME_EMAIL_TEMPLATE_ID:d-94f93354b8674d4197d850c5a1081c1c}
    kyb-kyc-pass-email-template-id: ${SENDGRID_KYB_KYC_PASS_EMAIL_TEMPLATE_ID:d-f7752da98ef540c79f872a1eae3666e5}
    kyb-kyc-fail-email-template-id: ${SENDGRID_KYB_KYC_FAIL_EMAIL_TEMPLATE_ID:d-651a88210bb54bbc92225150a2a211ce}
    forgot-password-email-template-id: ${SENDGRID_FORGOT_PASSWORD_EMAIL_TEMPLATE_ID:d-22ff7bff6c9c4c9d8692d826ca007eeb}
  stripe:
    secret: "whsec_Mj59eXcGrzLDhheRIb7cXk8mfwUhPfCI"
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID:AC08834a8aab6f817ea96ae7149e8befff}
    auth-token: ${TWILIO_AUTH_TOKEN:683c37c5aab1416ce35358132e457f2b}
    message-service-id: ${TWILIO_MESSAGE_SERVICE_ID:MGe85d68add5ac0ddb5a2526241aa0369f}
    verify-service-id: ${TWILIO_VERIFY_SERVICE_ID:VAbaf002bd328d70c5aadf45f92d8c49ac}
  clearbit:
    api-key: ${CLEARBIT_API_KEY:sk_2f09108fb81c88e6874543afaefac99c}

logging:
  level:
    root: INFO
    com.tranwall.capital: DEBUG

management:
  metrics:
    tags:
      application: capital-core
  endpoints:
    web:
      exposure:
        include: health,info,prometheus