package com.tranwall.capital.client.plaid;

/** from https://plaid.com/docs/errors/ */
public enum PlaidErrorCode {
  // Item errors
  ACCESS_NOT_GRANTED,
  INSTANT_MATCH_FAILED,
  INSUFFICIENT_CREDENTIALS,
  INVALID_CREDENTIALS,
  INVALID_MFA,
  INVALID_SEND_METHOD,
  INVALID_UPDATED_USERNAME,
  ITEM_CONCURRENTLY_DELETED,
  ITEM_LOCKED,
  ITEM_LOGIN_REQUIRED,
  ITEM_NOT_FOUND,
  ITEM_NOT_SUPPORTED,
  ITEM_NO_ERROR,
  MFA_NOT_SUPPORTED,
  NO_ACCOUNTS,
  NO_AUTH_ACCOUNTS,
  NO_INVESTMENT_ACCOUNTS,
  NO_INVESTMENT_AUTH_ACCOUNTS,
  NO_LIABILITY_ACCOUNTS,
  PRODUCT_NOT_ENABLED,
  PRODUCT_NOT_READY,
  PRODUCTS_NOT_SUPPORTED,
  USER_INPUT_TIMEOUT,
  USER_SETUP_REQUIRED,

  // Institution errors
  INSTITUTION_DOWN,
  INSTITUTION_NO_LONGER_SUPPORTED,
  INSTITUTION_NOT_AVAILABLE,
  INSTITUTION_NOT_ENABLED_IN_ENVIRONMENT,
  INSTITUTION_NOT_FOUND,
  INSTITUTION_NOT_RESPONDING,
  INSTITUTION_REGISTRATION_REQUIRED,
  UNAUTHORIZED_INSTITUTION,

  // API errors
  INTERNAL_SERVER_ERROR,
  PLANNED_MAINTENANCE,

  // Assets errors
  DATA_UNAVAILABLE,
  ASSET_REPORT_GENERATION_FAILED,
  INVALID_PARENT,
  INSIGHTS_NOT_ENABLED,
  INSIGHTS_PREVIOUSLY_NOT_ENABLED,

  // Payment errors
  PAYMENT_BLOCKED,
  PAYMENT_CANCELLED,
  PAYMENT_INSUFFICIENT_FUNDS,
  PAYMENT_INVALID_RECIPIENT,
  PAYMENT_INVALID_REFERENCE,
  PAYMENT_INVALID_SCHEDULE,
  PAYMENT_REJECTED,

  // Bank transfers errors
  BANK_TRANSFER_LIMIT_EXCEEDED,
  BANK_TRANSFER_MISSING_ORIGINATION_AMOUNT,
  BANK_TRANSFER_INVALID_ORIGINATION_AMOUNT,
  BANK_TRANSFER_ACCOUNT_BLOCKED,
  BANK_TRANSFER_INSUFFICIENT_FUNDS,
  BANK_TRANSFER_NOT_CANCELLABLE,
  BANK_TRANSFER_UNSUPPORTED_ACCOUNT_TYPE,
  BANK_TRANSFER_UNSUPPORTED_ENVIRONMENT,
  BANK_TRANSFER_FORBIDDEN_ACH_CLASS,

  // Deposit switch errors
  INVALID_DEPOSIT_SWITCH_ID,
  DEPOSIT_SWITCH_NOT_FOUND,
  DEPOSIT_SWITCH_TOKEN_NOT_FOUND,
  DEPOSIT_SWITCH_INVALID_ACCOUNT,
  DEPOSIT_SWITCH_VALID_AUTH_NOT_FOUND,
  DEPOSIT_SWITCH_VALID_IDENTITY_NOT_FOUND,
  DEPOSIT_SWITCH_ALREADY_COMPLETED,

  // Income errors
  INCOME_VERIFICATION_NOT_FOUND,
  INCOME_VERIFICATION_UPLOAD_ERROR,
  INCOME_VERIFICATION_DOCUMENT_INVALID,
  INCOME_VERIFICATION_DOCUMENT_NOT_RECOGNIZED,
  INCOME_VERIFICATION_FAILED,

  // Sandbox errors
  SANDBOX_PRODUCT_NOT_ENABLED,
  SANDBOX_WEBHOOK_INVALID,
  SANDBOX_BANK_TRANSFER_EVENT_TRANSITION_INVALID,

  // Invalid request errors
  MISSING_FIELDS,
  UNKNOWN_FIELDS,
  INVALID_FIELD,
  INVALID_CONFIGURATION,
  INCOMPATIBLE_API_VERSION,
  INVALID_BODY,
  INVALID_HEADERS,
  NOT_FOUND,
  NO_LONGER_AVAILABLE,
  SANDBOX_ONLY,
  INVALID_ACCOUNT_NUMBER,

  // Invalid input errors
  TOO_MANY_VERIFICATION_ATTEMPTS,
  INCORRECT_DEPOSIT_AMOUNTS,
  UNAUTHORIZED_ENVIRONMENT,
  INVALID_PRODUCT,
  USER_PERMISSION_REVOKED,
  UNAUTHORIZED_ROUTE_ACCESS,
  DIRECT_INTEGRATION_NOT_ENABLED,
  INVALID_API_KEYS,
  INVALID_ACCESS_TOKEN,
  INVALID_PUBLIC_TOKEN,
  INVALID_LINK_TOKEN,
  INVALID_PROCESSOR_TOKEN,
  INVALID_AUDIT_COPY_TOKEN,
  INVALID_ACCOUNT_ID,
  INVALID_STRIPE_ACCOUNT,
  INVALID_INSTITUTION,
  INVALID_CREDENTIAL_FIELDS,
  INVALID_PRODUCTS,
  PRODUCT_UNAVAILABLE,
  INVALID_WEBHOOK_VERIFICATION_KEY_ID,
  INVALID_LINK_CUSTOMIZATION,

  // Invalid result errors
  PLAID_DIRECT_ITEM_IMPORT_RETURNED_INVALID_MFA,

  // Rate limit exceeded errors
  ACCOUNTS_LIMIT,
  ADDITION_LIMIT,
  AUTH_LIMIT,
  BALANCE_LIMIT,
  IDENTITY_LIMIT,
  ITEM_GET_LIMIT,
  RATE_LIMIT,
  TRANSACTIONS_LIMIT,

  // Link web errors
  INSTITUTION_POOR_HEALTH_ERROR,
  OAUTH_ERROR,

  // ReCAPTCHA errors
  RECAPTCHA_REQUIRED,
  RECAPTCHA_BAD,

  // OAuth errors
  INCORRECT_OAUTH_NONCE,
  INCORRECT_LINK_TOKEN,
  OAUTH_STATE_ID_ALREADY_PROCESSED,
  OAUTH_STATE_ID_NOT_FOUND
}
